export const FETCH_LOGIN = "FETCH_LOGIN";
export const FETCH_LOGOUT = "FETCH_LOGOUT";

export const FETCH_INDEX = "FETCH_INDEX";
export const FETCH_FILTER = "FETCH_FILTER";

export const FETCH_FORECAST_INDEX = "FETCH_FORECAST_INDEX";
export const FETCH_FORECAST_FILTER = "FETCH_FORECAST_FILTER";

export const FETCH_SEVERAL_FILTER = "FETCH_SEVERAL_FILTER";
export const FETCH_SEVERAL_RECTANGLE = "FETCH_SEVERAL_RECTANGLE";
export const FETCH_SEVERAL_CIRCLE = "FETCH_SEVERAL_CIRCLE";
